---
- name: All environment
  hosts: all
  become: yes
  gather_facts: no
  roles:
   - all

- name: Build environment
  hosts: build
  become: yes
  gather_facts: no
  roles:
   - build
- name: Prod environment
  hosts: prod
  become: yes
  gather_facts: no
  roles:
   - prod